### ISSUE TITLE
Skipping target "FodyTarget" because all output files are up-to-date with respect to the input files.

### ISSUE THREAD

**Issue by vincenormand** [Fody/Fody#351] opened 2017-05-31 14:46 UTC
With version 2.0.10 of Fody, the file "Fody.targets" has changed.

I do not know why, but because of this, my project does not execute Fody in Release mode. It works well in Debug mode.
I think it is due to "CryptoObfuscator 2015 RC" being configured on this project and obfuscating on Release.

When i disable the obfuscation, Fody gets executed.
When i enable it, i get this message in the Output window : 
```
FodyTargets:
Skipping target "FodyTarget" because all output files are up-to-date with respect to the input files.
```

If i replace the "Fody.targets" file with the old one from Fody version 1.29.4, Fody gets executed in Debug and Release mode correctly, and with obfuscation enabled.

Would you have any idea of what could cause this problem?
What has been changed in the "Fody.targets" that could cause this?

Thank you

EDIT :
In the "Fody.targets", if i remove line 50 where it says "Inputs="...",, Fody gets executed :

```
<Target
      AfterTargets="AfterCompile"
      Condition="Exists('@(IntermediateAssembly)')"
      Name="FodyTarget"
      DependsOnTargets="$(FodyDependsOnTargets)"
      **Inputs="@(IntermediateAssembly->'%(FullPath)');$(FodyKeyFilePath);$(ProjectWeaverXml)"**
      Outputs="$(TargetPath)">

    <Fody.WeavingTask
          AssemblyPath="@(IntermediateAssembly)"
          IntermediateDir="$(ProjectDir)$(IntermediateOutputPath)"
          KeyFilePath="$(FodyKeyFilePath)"
          NuGetPackageRoot="$(NuGetPackageRoot)"
          ProjectDirectory="$(ProjectDir)"
          SolutionDir="$(FodySolutionDir)"
          References="@(ReferencePath)"
          SignAssembly="$(FodySignAssembly)"
          ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)"
          DefineConstants="$(DefineConstants)"
          PackageDefinitions="@(PackageDefinitions->'%(ResolvedPath)')"
          DebugSymbols="$(DebugSymbols)"
      >

      <Output 
        TaskParameter="ExecutedWeavers"
        PropertyName="FodyExecutedWeavers" />
    </Fody.WeavingTask>

    <PropertyGroup>
      <FodyWeavingTargetWasRun>True</FodyWeavingTargetWasRun>
    </PropertyGroup>

  </Target>

```

**Comment by SimonCropp** [comment] 2017-06-03 01:26
please reformat your issue so the code read correctly

**Comment by vincenormand** [comment] 2017-06-05 13:09
Done

**Comment by distantcam** [comment] 2017-06-05 13:22
There was a problem with Fody builds and Release config. Try upgrading to
Fody 2.1.

**Comment by vincenormand** [comment] 2017-06-05 13:40
I upgraded to Fody 2.1, but i still get the same problem...

**Comment by distantcam** [comment] 2017-06-05 13:45
Well, it was a long shot anyway.

**Comment by distantcam** [comment] 2017-06-05 14:12
@vincenormand Are you sure this is working in Debug mode?

So the problem is, CryptoObfuscator is running during `AfterCompile` (replacing the task) while Fody runs after the `AfterCompile` task. CryptoObfuscator modifies the assembly from obj and moves it to bin. Fody then modifies the assembly from obj and moves it to bin, overwriting whatever CryptoObfuscator does.

Not sure the best way to fix this yet. I'm still investigating.

**Comment by vincenormand** [comment] 2017-06-05 15:10
100% sure it is working in Debug mode.

But wouldn't it be more logical if Fody could run before CryptoObfuscator?
It might not be possible though... i don't know.

**Comment by distantcam** [comment] 2017-06-05 15:31
After further investigating it looks like CryptoObfuscator writes its output to both obj and bin, even though it says it's only writing to bin.

At this point I suspect your best bet is to either handle running CryptoObfuscator in a custom target file that runs it after Fody, or contacting LogicNP Software for support.

**Comment by SimonCropp** [comment] 2017-06-06 21:37
@vincenormand have u raised it with CryptoObfuscator   ?

**Comment by SimonCropp** [comment] 2017-06-06 21:50
is cryptoobfuscator even still in business? their Copyright is "Copyright © 2007-2015 LogicNP Software." and their website looks like it is stuck in the 90s

**Comment by distantcam** [comment] 2017-06-07 06:45
Here's a custom target file to use in place of CryptoObfuscators.

Change the line `<Import Project="C:\Program Files (x86)\LogicNP Software\Crypto Obfuscator For .Net 2015\CryptoObfuscator.targets" />`
to `<Import Project="CryptoObfuscator.targets" />`

Then add this file to your project as `CryptoObfuscator.targets`

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask TaskName="CryptoObfuscator" AssemblyFile="C:\Program Files (x86)\LogicNP Software\Crypto Obfuscator For .Net 2015\MSBuildIntegration.dll" />
  <Target Name="CryptoObfuscator_BeforeCompile" BeforeTargets="BeforeCompile" Condition=" ('$(Configuration)|$(Platform)' == '$(CO_Config)' Or '$(Configuration)' == '$(CO_Config)') And $(CO_FirstProject)=='True' ">
    <CryptoObfuscator ProjectFile="$(CO_ProjectFilePath)" BeforeBuild="True" LC="$(CO_LC)" CheckFullLicense="$(CO_CheckFullLicense)" />
  </Target>
  <Target Name="CryptoObfuscator_AfterCompile" AfterTargets="AfterCompile;FodyTargets" Condition=" ('$(Configuration)|$(Platform)' == '$(CO_Config)' Or '$(Configuration)' == '$(CO_Config)') And $(CO_LastProject)=='True'">
    <CryptoObfuscator ProjectFile="$(CO_ProjectFilePath)" LC="$(CO_LC)" CheckFullLicense="$(CO_CheckFullLicense)" BuildID="$(CO_BuildID)" MapFilesLocation="$(CO_MapFilesLocation)" FailOnUnsuppressedWarning="$(CO_FailOnUnsuppressedWarning)" SaveWarningsToFile="$(CO_SaveWarningsToFile)" SaveSuppressedWarnings="$(CO_SaveSuppressedWarnings)" SaveUnsuppressedWarnings="$(CO_SaveUnsuppressedWarnings)" AdditionalParameters="$(CO_AdditionalParameters)">
      <Output TaskParameter="Executed" PropertyName="CO_Executed" />
    </CryptoObfuscator>
    <Copy SourceFiles="@(CO_ObjFiles)" DestinationFiles="@(CO_BinFiles)" Condition=" '$(CO_Executed)' == 'True' " />
  </Target>
  <Target Name="CryptoObfuscator_AfterBuild" AfterTargets="AfterBuild" Condition=" ('$(Configuration)|$(Platform)' == '$(CO_Config)' Or '$(Configuration)' == '$(CO_Config)') And $(CO_XapProject)=='True' ">
    <CryptoObfuscator ProjectFile="$(CO_ProjectFilePath)" LC="$(CO_LC)" CheckFullLicense="$(CO_CheckFullLicense)" BuildID="$(CO_BuildID)" MapFilesLocation="$(CO_MapFilesLocation)" FailOnUnsuppressedWarning="$(CO_FailOnUnsuppressedWarning)" SaveWarningsToFile="$(CO_SaveWarningsToFile)" SaveSuppressedWarnings="$(CO_SaveSuppressedWarnings)" SaveUnsuppressedWarnings="$(CO_SaveUnsuppressedWarnings)" AdditionalParameters="$(CO_AdditionalParameters)">
      <Output TaskParameter="Executed" PropertyName="CO_Executed" />
    </CryptoObfuscator>
    <Copy SourceFiles="$(CO_XapOutput)" DestinationFiles="$(OutputPath)$(XapFilename)" Condition=" '$(CO_Executed)' == 'True' " />
  </Target>
</Project>
```

**Comment by vincenormand** [comment] 2017-06-15 12:16
Sorry for the delay, I have been busy working on other things.

I haven't raised it to CryptoObfuscator.

Changing the Targets of Crypto is one solution, but we managed to fix this by modifying the .csproj of our project so that Crypto is dependent on Fody.
This way, Fody runs first, then Crypto.

I will try to post the code soon.

**Comment by vincenormand** [comment] 2017-06-16 13:01
Here it is :
```
<Target Name="HACK_CryptoObfuscator" DependsOnTargets="FodyTarget" BeforeTargets="AfterCompile">
  <Message Text="*** Force Fody to run before CryptoObfuscator ***" />
</Target>
```

**Comment by SimonCropp** [comment] 2017-10-22 01:29
since u have a workaround, i i would prefer not to hard code assumptions into fody related to an abandoned product that gives the perception of security, i am closing this

**Closed by SimonCropp** 2017-10-22 01:29 UTC
