### ISSUE TITLE
Debug problem when embedding the assamblys!

### ISSUE THREAD

**Issue by Hendrik-Koelbel** [Fody/Fody#723] opened 2019-07-17 07:38 UTC
> Zur Information: Ich nutze Fody/Costura und den [Resource.Embedder](https://github.com/MarcStan/Resource.Embedder)

**Expected behaviour**:

The program should embed all dlls and satellite assemblies with every debug no matter if changes have been made or not.

**Actual behaviour:**

The program only embeds all dlls when changes have been made to the program. With multiple debugging without changes to the Windows form, the dlls are no longer embedded but the satellite assemblies are.

**Steps to reproduce the problem:**
First I created a test app to test this and it turned out that this error always occurs.
**[Test App Link](https://github.com/Hendrik-Koelbel/Test_Application)**

 **1. I debug my program and it is perfectly embedded.**

![first_run_good_embedded](https://user-images.githubusercontent.com/31684940/61354720-16e01380-a873-11e9-9105-5bc4d70d372e.png)

  **2. I debug again without having made any changes and it only embeds the language dlls but not the other assemblies like newtonsoft.json.dll or costura.dll**

![second_run_with_failed_embedding](https://user-images.githubusercontent.com/31684940/61354733-1f384e80-a873-11e9-9bff-22b316e5a2b5.png)

  **3. I changed the size of the form or a text and debugged it again. After that everything is properly embedded again.**

![third_run_after_size_change_good_embedded](https://user-images.githubusercontent.com/31684940/61354744-23fd0280-a873-11e9-9530-9d2c4c658786.png)

>**Sometimes a System.BadImageFormatException also appears but this error remains.**

![third_run_this_error_comes](https://user-images.githubusercontent.com/31684940/61356046-d1711580-a875-11e9-9263-ec03d1d9da03.png)

**Details:**

  - .Net Version: v4.7.2
  - Platform/OS Version: Windows 10
  - Additional details: Visual Studio 2019

**Comment by SimonCropp** [comment] 2019-07-17 08:54
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.

**Comment by Hendrik-Koelbel** [comment] 2019-07-17 09:54
> [Issues from non-Patrons, that are bugs and are highly likely to effect the larger Fody user base, may justify the effort and be handled.](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue)

@SimonCropp I think the issue is general to all Fody users.
Since this is only noticeable when debugging several times without making any changes to the software in the meantime, this issue is not so common.
Please take a look at the issue, as I think it might occur to all users.

**Comment by SimonCropp** [comment] 2019-07-17 10:47
given you are so far the only one to report this, i will wait to see how many other people report to have had the same issue, and then make a decision. if you want it fixed sooner, i am happy to consider a PR.

Other than that, if this is a blocker for you, perhaps stop using Fody.

**Comment by Hendrik-Koelbel** [comment] 2019-07-19 06:58
I think Fody is the best way to embed assemblies into debugging, so I will continue to use it in the future. 

> I have now downgraded my Fody version to 3.3.5 and Costura version to 3.3.2.
> So everything works again!

I've also found **four other developers** who could reproduce the same problem and I just ask you to **take a look on it in your own interest**. 

After fixing the bug, I will also be happy to consider PR!

**Comment by SimonCropp** [comment] 2019-07-19 08:18
By PR i meant a pull request https://help.github.com/en/articles/about-pull-requests

As in “if this is important to you, feel free to fix it and submit a PR”

I assume the four other developers are patrons?

**Comment by SimonCropp** [comment] 2019-07-19 20:19
I looked into this a little further. 

>  I debug again without having made any changes and it only embeds the language dlls but not the other assemblies like newtonsoft.json.dll or costura.dll

this is incorrect. costura.dll is never embedded. it is a limitation of the the old nuget system that it gets copied over. set "Copy local - false" in the reference and that will not occur. of `<Private>False</Private>` in the csproj

```
    <Reference Include="Costura, Version=4.0.0.0, Culture=neutral, PublicKeyToken=9919ef960d84173d, processorArchitecture=MSIL">
      <HintPath>..\packages\Costura.Fody.4.0.0\lib\net40\Costura.dll</HintPath>
      <Private>False</Private>
    </Reference>
```

newtonsoft is still embedded correctly. have a look at the exe in ILSpy and you will see the embedded resource. if you deploy your exe without Costura.dll and files it will still run. the same with the `de` resources. this seems to be a qwerk if the old project system. it is incorrectly doing a triggering the `AfterCompile` msbuild target when no compile has occurred, hence fody giving a warning about re-running on the same assembly.

I was unable to reproduce these problems in the new sdk style of csproj

given the old project system is essentially deprecated by MS, i am unlikely to be able to justify  the effort involved (likely several hours) of debugging and fixing this.

given this wont be fixed I suggest you stop using Fody.

I was not able to reproduce the BadImageFormatException

**Closed by SimonCropp** 2019-07-19 20:19 UTC
