### ISSUE TITLE
error CS0103: The name '...' does not exist in the current context, fody removing using statements?

### ISSUE THREAD

**Issue by DigitalZilla** [Fody/Fody#320] opened 2017-04-28 20:56 UTC
I'm not sure if this is an issue with PropertyChanged.Fody or Fody in general, but it appears that some of my Using statements are removed.  I don't understand why it's happening, as the compiled code runs fine without fully qualified paths, but when I try to put something in the watch window (such as Process.GetProcesses()), the debugger tells me that _Process_ doesn't exist in the current scope, even though it clearly is.  If I type in the fully qualified path, then the watch window works fine, but this makes mouse-over debugging (and a lot of the really powerful features of OzCode) not work.

![fodyusing](https://cloud.githubusercontent.com/assets/18022018/25546855/b31355c4-2c19-11e7-8d0a-4b101f2431da.jpg)

**Comment by SimonCropp** [comment] 2017-04-28 22:50
Does it happen when running in Debug mode

**Comment by DigitalZilla** [comment] 2017-04-28 23:10
That is a screenshot from debug mode, yes.

**Comment by SimonCropp** [comment] 2017-05-27 03:50
there were some cope fixes in the recent release of cecil. can u verify it still happens with 2.0.10

**Comment by DigitalZilla** [comment] 2017-05-31 16:34
2.0.10 seems to be working correctly, Thank you!

**Comment by DigitalZilla** [comment] 2017-05-31 17:15
It looks like I spoke too soon.  2.0.10 fixed some issues, but not all issues.  It appears that the using statements now correctly work, however, it seems like the current namespace is not taken into account.

In the below image, you can see I have a class _Settings_ that lives inside the namespace _FodyUsing.Properties_ (just a standard project settings file created in the project properties editor).   I can access the Settings class by prefixing it with **Properties** because i'm already inside the _FodyUsing_ namespace.  However, down in the watch window, I have to manually add the _FodyUsing_ namespace even though it should be implied.  If I disable Fody, the issue goes away.

![fodynamespace](https://cloud.githubusercontent.com/assets/18022018/26644363/4b08e266-45e9-11e7-86e1-2c4d543b2b50.jpg)

**Comment by DigitalZilla** [comment] 2017-06-12 16:40
Just wanted to bump this to make sure there were some eyes on it.  Thanks!

**Comment by SimonCropp** [comment] 2017-09-24 10:06
duplicate of https://github.com/Fody/Fody/issues/130

**Closed by SimonCropp** 2017-09-24 10:06 UTC

**Comment by DigitalZilla** [comment] 2017-09-25 15:11
As mentioned in the other bug, the new version (2.1.2) seems to have fixed the second issue.
Thanks.
