### ISSUE TITLE
Vs.net IDE0006 issue

### ISSUE THREAD

**Issue by lu8848** [Fody/Fody#301] opened 2017-04-07 00:06 UTC
When I open a c# project, vs.net shows warning in Error List tab page: "Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled." The error details in vs.net design time log file is "MSBUILD : error : Fody: AssemblyPath "C:\...\obj\Debug\....dll" does not exists. If you have not done a build you can ignore this error."

My environment: VS Entriprise 2015 Update3, Fody 1.29.4

**Comment by c0nnex** [comment] 2017-04-10 21:46
It's a porblem of  windows not fody. 
Since WIndows Creator update i have the same problem. It comes and goes.
Sometimes complaining about dll not found (checking that dll it turns out it's length zero) , sometime cannot open stronkey. It seems to be a problems that something lilke Windows Defender blocks those sometimes.

**Comment by SimonCropp** [comment] 2017-04-22 15:43
Can u share a repro

**Comment by c0nnex** [comment] 2017-04-22 23:31
Sorry private repro. But as it looks like it only happens to projects where Targetdirectory != default.
But definitly a windows issue. I reverted from latest insider to public windows release and all is fine again.

**Comment by SimonCropp** [comment] 2017-04-23 01:42
have u raised it with MS?

**Comment by cremor** [comment] 2017-04-26 05:23
I sometimes get the same warning from VS 2015 Update 3, but I'm using Windows 7. So it isn't related to the Creators Update or Windows 10 at all.
I don't know how to consistently reproduce it. Usually I just close VS completely and the next time I open my solution the warnings are gone.

**Comment by SimonCropp** [comment] 2017-05-27 03:51
i suspect this might be fixed in Fody 2.0.11-beta0001. can u test it?

**Closed** 2017-08-15 20:44 UTC
