### ISSUE TITLE
Breaking change in version 2.1.3?

### ISSUE THREAD

**Issue by hrafnl** [Fody/Fody#409] opened 2017-10-11 13:28 UTC
I have version 2.1.2 of Fody installed in my Xamarin project, for the purpose of PropertyChanged, and it works fine.  When installing version 2.1.3 of Fody, the app breaks in the sense that the UI's (list views) are not updated with data coming from a web service.

Example:
```
public List<Member> MemberList { get; set; }

           try
            {
                this.MemberList = null;
                this.BeginLoading();
		await Task.Delay(DelayForTask);
                this.MemberList = await this.SomeService.GetMembers();
            }
            catch (Exception e)
            {
                this.ReportException(e);
            }
            finally
            {
                this.EndLoading();
            }
```

And in the XAML:

```
<ListView x:Name="MemberListView"
                ItemsSource="{Binding MemberList}"
                IsVisible="True"
                ItemSelected="OnItemSelected"
                SelectedItem="{Binding SelectedMember,Mode=TwoWay}"
                IsPullToRefreshEnabled="{Binding Retrieving, Converter={StaticResource InverseBooleanConverter}}"
                IsRefreshing="{Binding Refreshing}"
                RefreshCommand="{Binding RefreshCommand}"     
```
Here, MemberList contains the data, but does not show up in the view.

Any idea what causes this?

**Comment by SimonCropp** [comment] 2017-10-11 19:32
Please upload a small solution that reproduces the problem

**Comment by sushihangover** [comment] 2017-10-12 16:02
I have a similar issue with `Realm`, updating Fody from `2.1.2` to `2.1.3` is causing the RealmWeaver task to not process correctly. Something in "new" version of  `Mono.Cecil` being used possibly?

Re: https://github.com/realm/realm-dotnet/issues/1593

I'll see if I can get a repro project together.

**Comment by hrafnl** [comment] 2017-10-12 19:14
Here is a small project, for which the problem can be reproduced: https://github.com/hrafnl/testFody/

1) Clone the project and build the solution
2) Run the iOS or Droid project (in a simulator)
3) Notice that data appears on the page
4) Install Fody 2.1.3 (instead of 2.1.2)
5) Rebuild and run either project
6) Notice that the data does not appear on the page

**Comment by Khorynthium** [comment] 2017-10-13 10:43
Faced this issue yesterday. Looks like binary partis fine, problem is in installation routine, fody.target import hasn't been added into csproject file during package update.

**Comment by SimonCropp** [comment] 2017-10-13 10:50
Are you using a supported runtime?

**Comment by SimonCropp** [comment] 2017-10-13 10:50
https://github.com/Fody/Fody#supported-runtimes

**Comment by Khorynthium** [comment] 2017-10-13 10:58
No. Unfortunately that project is still on 4.5.1. It's not an issue for me, I just downgraded to a previous version. I only shared my observations regarding this problem. :)

**Comment by SolutionSoftwareMaexx** [comment] 2017-10-13 11:16
Same problem.
Framework is 4.6.1

Fody Version 2.1.2
PropertyChanged.Fody 2.1.4

Everything works fine.

Update to Fody Version 2.1.3. Nothing works. There are no PropertyChanged Events.

**Comment by SimonCropp** [comment] 2017-10-15 00:37
@hrafnl u seem to be using an unsupported runtime https://github.com/hrafnl/testFody/blob/master/testFody/testFody/testFody.csproj#L13

**Comment by SimonCropp** [comment] 2017-10-15 00:38
ok i am closing this. if someone can show me a repro against a supported runtime https://github.com/Fody/Fody#supported-runtimes i am more than happy to re-open and debug into it

**Closed by SimonCropp** 2017-10-15 00:38 UTC
