### ISSUE TITLE
Windows Universal Library - Fielder

### ISSUE THREAD

**Issue by Nicothekrug** [Fody/Fody#195] opened 2015-08-11 08:27 UTC
Hi,

I used PropertyChanged in multiple projects but with a new win10 one i'm having trouble.
Using your documentation, I'm able to install Fody and PropertyChanged with no problem in a Windows Universal Library (win 10).
But Fielder is also needed, and i cant figure out a way to install it. 
Via nuget PropertyChanged install perfectly : 

PM> install-package PropertyChanged.Fody
Restoring packages for 'XXX'.
Restoring packages for XXX...
Restoring packages for UAP,Version=v10.0...
Restoring packages for UAP,Version=v10.0 (win10-arm)...
Restoring packages for UAP,Version=v10.0 (win10-arm-aot)...
Restoring packages for UAP,Version=v10.0 (win10-x86)...
Restoring packages for UAP,Version=v10.0 (win10-x86-aot)...
Restoring packages for UAP,Version=v10.0 (win10-x64)...
Restoring packages for UAP,Version=v10.0 (win10-x64-aot)...
All packages are compatible with UAP,Version=v10.0.
All packages are compatible with UAP,Version=v10.0 (win10-arm).
All packages are compatible with UAP,Version=v10.0 (win10-arm-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x86).
All packages are compatible with UAP,Version=v10.0 (win10-x86-aot).
All packages are compatible with UAP,Version=v10.0 (win10-x64).
All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore completed successfully for 'XXX'.
Generating MSBuild file XXX.nuget.targets.
Successfully installed 'PropertyChanged.Fody 1.50.3' to XXX

But i don't know what happens with Fielder :

PM> install-package Fielder.Fody
Restoring packages for 'XXX'.
Restoring packages for XXX\project.json...
Restoring packages for UAP,Version=v10.0...
install-package : Unable to resolve Fielder.Fody (≥ 1.0.10) for UAP,Version=v10.0.
At line:1 char:1
+ install-package Fielder.Fody
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Package restore failed for 'XXX'.
install-package : Package restore failed. Rolling back package changes for 'XXX'.
At line:1 char:1
+ install-package Fielder.Fody
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Is this a known behaviour ? Is there a workaround ?

By the way, impressive work, great job !

**Comment by SimonCropp** [comment] 2015-08-11 09:56
i cant reproduce this. 

can u try

> install-package Fielder.Fody -version 1.0.10

**Comment by SimonCropp** [comment] 2015-08-11 09:57
if that doesnt work suggest raise an issue here https://github.com/NuGet/Home and link to this

**Comment by Nicothekrug** [comment] 2015-08-12 07:48
I tried it, this command raises the same error. Kinda weird.

As you suggested, i have raised an issue on NuGet. 
Thank you for your quick replies. I'll let you know.

**Comment by Nicothekrug** [comment] 2015-08-12 09:27
FYI : "this package version is missing from the NuGet v3 feed"

**Comment by SimonCropp** [comment] 2015-10-01 02:12
closing this as a nuget issue

**Closed by SimonCropp** 2015-10-01 02:12 UTC
