### ISSUE TITLE
"Fody.WeavingTask" task failed unexpectedly

### ISSUE THREAD

**Issue by SimplerSoftware** [Fody/Fody#439] opened 2017-12-20 20:46 UTC
I've looked at the other issues with the same error but none have helped.  I'm trying to build a .Net Core 2.0 project using the cli: dotnet Build [projectname.csproj].  The error is regarding a referenced project which is targeting .Net Standard 2.0.  Is .Net Standard 2.0 supported?

The build fails with the following error:

C:\Users\steve\.nuget\packages\fody\2.3.3\build\netstandard1.0\Fody.targets(54,5): error MSB4018: The "Fody.WeavingTask" task failed unexpectedly. [C:\GIT\R365New\Application\R365.Domain\R365.Domain.csproj]
C:\Users\steve\.nuget\packages\fody\2.3.3\build\netstandard1.0\Fody.targets(54,5): error MSB4018: System.TypeInitializationException: The type initializer for 'ContainsTypeChecker' threw an exception. ---> System.TypeLoadException: Could not load type 'System.AppDomainSetup' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. [C:\GIT\R365New\Application\R365.Domain\R365.Domain.csproj]
C:\Users\steve\.nuget\packages\fody\2.3.3\build\netstandard1.0\Fody.targets(54,5): error MSB4018:    at ContainsTypeChecker..cctor() [C:\GIT\R365New\Application\R365.Domain\R365.Domain.csproj]
C:\Users\steve\.nuget\packages\fody\2.3.3\build\netstandard1.0\Fody.targets(54,5): error MSB4018:    --- End of inner exception stack trace --- [C:\GIT\R365New\Application\R365.Domain\R365.Domain.csproj]
C:\Users\steve\.nuget\packages\fody\2.3.3\build\netstandard1.0\Fody.targets(54,5): error MSB4018:    at Fody.WeavingTask.Execute() [C:\GIT\R365New\Application\R365.Domain\R365.Domain.csproj]
C:\Users\steve\.nuget\packages\fody\2.3.3\build\netstandard1.0\Fody.targets(54,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() in E:\A\_work\8\s\src\Build\BackEnd\TaskExecutionHost\TaskExecutionHost.cs:line 631 [C:\GIT\R365New\Application\R365.Domain\R365.Domain.csproj]
C:\Users\steve\.nuget\packages\fody\2.3.3\build\netstandard1.0\Fody.targets(54,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() in E:\A\_work\8\s\src\Build\BackEnd\Components\RequestBuilder\TaskBuilder.cs:line 787 [C:\GIT\R365New\Application\R365.Domain\R365.Domain.csproj]

Any help is greatly appreciated. Thanks

**Comment by SimonCropp** [comment] 2017-12-24 20:24
Netstandard and net core are supported. But dotnet build is not yet supported. You need to use msdbuild atm 

Duplicate of https://github.com/Fody/Fody/issues/374

**Closed by SimonCropp** 2017-12-24 20:24 UTC
