### ISSUE TITLE
bug MSBUILD : error : Fody: Found no debug symbols.

### ISSUE THREAD

**Issue by Furtif** [Fody/Fody#316] opened 2017-04-26 22:02 UTC
Appveyor bug    Fody: Fody (version 2.0.5.0) Executing
MSBUILD : error : Fody: Found no debug symbols. [c:\projects\rocketbot2\RocketBot2\RocketBot2.csproj]
    Fody:   Finished Fody 1302ms.
Command exited with code 1

Any ideas??

**Comment by SimonCropp** [comment] 2017-04-26 23:59
Is it a public project?

**Comment by Furtif** [comment] 2017-04-27 00:03
hello @SimonCropp https://ci.appveyor.com/project/RocketBot/rocketbot/build/0.0.0.229
yes a public project, thanks for your answer

**Comment by SimonCropp** [comment] 2017-04-27 00:06
i suspect it is a duplicate of https://github.com/Fody/Fody/issues/309

**Comment by CDAGaming** [comment] 2017-04-27 00:07
Yea, we are on the same/similar projects with the same errors, with the same versions of Fody Effected :P

**Comment by Furtif** [comment] 2017-04-27 00:08
In local all goes well it is just in appveyor the bug ok ok i seen #309 thanks i close it

**Closed** 2017-04-27 00:08 UTC

**Comment by SkyGen** [comment] 2017-11-20 20:21
I am getting this error (MSBUILD : warning : Fody: No debug symbols found) with Fody 2.2.1, but ONLY with a release compile; it compiles debug without warnings.  Is it an MSBUILD issue or a Fody issue?

**Comment by SkyGen** [comment] 2017-11-20 20:23
Excuse the last post; I meant a warning (not error).  I am using Fody 2.2.1 with PropertyChanged.Fody 2.1.4.

**Comment by SkyGen** [comment] 2017-11-20 20:31
More info: I tried suppressing all MSBUILD warnings with "/p:WarningLevel=0" but it did NOT suppress the  (MSBUILD : warning : Fody: No debug symbols found) warning.  I get this error when building Release (not Debug).
