### ISSUE TITLE
Xamarin Studio problem

### ISSUE THREAD

**Issue by acaliaro** [Fody/Fody#155] opened 2015-02-10 16:59 UTC
Hi, I-ve updated today Xamarin Studio and Android SDK.
After the upgrade, I try to recompile my project in RELEASE mode (in DEBUG it works)
I've this error (sorry, it's in italian)

D:\Documenti\software\CSharpApp\ACaliaro\Crossware\Geco\Geco\packages\Fody.1.27.0\build\Fody.targets(5,5): Error MSB4044: all'attività "Fody.WeavingTask" non è stato assegnato un valore per il parametro obbligatorio "DefineConstants". (MSB4044) (Geco)

The error is here

 <Fody.WeavingTask
          AssemblyPath="@(IntermediateAssembly)"
          IntermediateDir="$(IntermediateDir)"
          KeyFilePath="$(FodyKeyFilePath)"
          ProjectDirectory="$(ProjectDir)"
          SolutionDir="$(FodySolutionDir)"
          References="@(ReferencePath)"
          SignAssembly="$(FodySignAssembly)"
          ReferenceCopyLocalPaths="@(ReferenceCopyLocalPaths)"
          DefineConstants="$(DefineConstants)"
      />

Can you help me?
Thanks

**Comment by SimonCropp** [comment] 2015-02-11 10:44
can u try 1.27.1-beta01

**Comment by acaliaro** [comment] 2015-02-11 12:15
Simon, where I find it?

----- Messaggio originale -----
Da: "Simon Cropp" <notifications@github.com>
Inviato: ‎11/‎02/‎2015 11:44
A: "Fody/Fody" <Fody@noreply.github.com>
Cc: "acaliaro" <acaliaro@libero.it>
Oggetto: Re: [Fody] Xamarin Studio problem (#155)

can u try 1.27.1-beta01

---

**Comment by SimonCropp** [comment] 2015-02-11 12:16
http://www.nuget.org/packages/Fody/1.27.1-beta01

**Comment by acaliaro** [comment] 2015-02-11 13:24
Simon, same problem...

**Comment by SimonCropp** [comment] 2015-02-12 03:14
can u please upload a repro of this somewhere

**Comment by acaliaro** [comment] 2015-02-12 07:14
Simon, I don’t know if it’s a fody problem or a xamarin problem.
Xamarin people have solved it modifing the csprj file I attach
Alessandro
“Copia” gives the error

**Comment by SimonCropp** [comment] 2015-02-16 10:39
duplicate of https://github.com/Fody/Fody/issues/159

**Closed by SimonCropp** 2015-02-16 10:39 UTC
