### ISSUE TITLE
Fody runs on un-built project?

### ISSUE THREAD

**Issue by benblo** [Fody/Fody#213] opened 2015-12-09 10:12 UTC
We have a weaver that creates/deletes a wrapper file for every type in the project. Those wrappers are source controlled. 
So suppose I add a new type to the project, and I commit it, with its wrapper. 
Now my coworker pulls, Visual Studio reloads the project, and apparently Fody runs (I assume) against his last compiled version of the project, which does not contains my new type, so our weaver deletes the wrapper.
Next time he compiles, the wrapper is recreated, but this has side-effects with our tools in our pipeline.

So my question is (assuming I've correctly identified the repro!), why is Fody running upon project reload, and not only when a build is triggered?

**Comment by SimonCropp** [comment] 2015-12-09 10:17
the problem is AfterCompile sometimes execute even when a compile has not occurred. i dont know why. so fody cant distinguish between "file missing due to some configuration problem" and "file missing because AfterCompile is being executed but no compile was done ".

If you can tell me how to detect the difference in the context of msbuild i will be happy to fix this

**Comment by benblo** [comment] 2015-12-09 11:26
Dammit... no, I have no idea as I really don't know much about the MSBuild event flow.
Isn't there a way to check timestamps to see if the DLL being processed has changed since the last time Fody ran?...

BTW my problem here isn't "file missing", but "Fody runs against an old version of a DLL".

**Comment by 0x53A** [comment] 2016-01-02 22:15
I have also noticed that sometimes Fody gets triggered "out of the blue". Could this be related to the background compilation by Roslyn in VS 2015?

**Comment by SimonCropp** [comment] 2016-01-02 23:48
@0x53A i would assume so. Any more info in the msbuild logs?

**Comment by SimonCropp** [comment] 2016-02-14 02:35
@benblo can u upload a repro for this somewhere?

**Comment by SimonCropp** [comment] 2016-02-14 05:25
should be fixed by https://github.com/Fody/Fody/commit/109a3a7e7498619b504a05d33bb2cc64dafd1c69

**Closed by SimonCropp** 2016-02-14 05:25 UTC
