### ISSUE TITLE
FodyWeavers.xml warnings

### ISSUE THREAD

**Issue by Logerfo** [Fody/Fody#613] opened 2018-11-28 11:43 UTC
Hello. I just upgraded from Fody version 3.2.4 to 3.3.2 and now I'm getting two new warnings:
> The element 'Weavers' cannot contain child element 'Costura' because the parent element's content model is empty.

> The element cannot contain white space. Content model is empty.

The first one happens for every weaver in any project. The second one only happens for projects where Fody is installed but no weaver is configured. I have a solution with multiple projects, but not all of them actually have weavers configured. I chose to install Fody in all of them for consistence reasons.

I think this is happening because of the new .xsd file, but I have zero knowledge about that stuff. I had to change the .xml files for two reasons:
1) To keep only one .xsd file for the whole solution. I temporarily rolled that back in order to make sure that this wasn't the issue cause.
2) The package didn't automatically changed my .xml files which are not named `FodyWeavers.xml`, which I use to deploy different weavers in debug and release mode, base on [this solution](https://github.com/Fody/Costura/issues/143#issuecomment-307963083).

**Comment by ltrzesniewski** [comment] 2018-11-28 11:58
Hi, these warnings are only IntelliSense warnings, and have no impact on the build. The xsd file is there just to provide xml schema information to VS so it can help you edit the xml file by detecting invalid configuration attributes and providing autocompletion.

The xsd file is generated when the project is built, and it describes the weavers that are installed in your project. You should have one xsd file per project, because each project can have different weavers installed. You're getting the first error most likely because you took the xsd from a project which does not use Costura.

As for the second error, if you really want to use Fody without any weaver, try writing:

```xml
<Weavers />
```

Instead of:

```xml
<Weavers>
</Weavers>
```

But I would recommend against it, since it _will_ negatively impact your compilation times for no good reason.

**Comment by Logerfo** [comment] 2018-11-28 12:18
I made a mistake: the second error also happens when there **are** weavers. Your solution worked for weaver-less files. Is there a way to disable those warnings? They keep growing and are annoying. I already have to deal with those:
> Fody: No configured weavers. It is possible no weavers have been installed or a weaver has been installed into a project type that does not support install.ps1. It may be necessary to manually add that weaver to FodyWeavers.xm;. eg.
```
<Weavers>
    <WeaverName/>
</Weavers>
``` 
see https://github.com/Fody/Fody/wiki/SampleUsage

**Comment by ltrzesniewski** [comment] 2018-11-28 12:38
You're probably getting these warnings because you took a xsd file from a project which has no weavers and applied it to a project which has weavers. If your xsd file contains a tag `<xs:all></xs:all>` without any content, that would explain it.

Can you tell me exactly:
- Why do you want to use Fody without weavers? This is reported as an error because in most cases it is one. The fix for this is to uninstall Fody in projects where you don't need it.
- Why don't you want to have one xsd file next to each FodyWeavers.xml file? This is the usage that Fody supports.

You can _probably_ get rid of all warnings if your replace your solution-level xsd file with this:

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Weavers" type="xs:anyType" />
</xs:schema>
```

But this is not a supported scenario and **I cannot guarantee** this will not break in the future. It should work today because Fody won't update the `xsi:noNamespaceSchemaLocation` attribute in FodyWeavers.xml if one exists. Also, Fody _will_ still generate a xsd file next to each FodyWeavers.xml file.

I guess we could probably add a configuration option which disables the new IntelliSense feature entirely, but if would be better if you could use the configuration files in the supported way.

**Comment by Logerfo** [comment] 2018-11-28 12:54
Your .xsd solution worked, thanks!

> It should work today because Fody won't update the xsi:noNamespaceSchemaLocation attribute in FodyWeavers.xml if one exists. Also, Fody will still generate a xsd file next to each FodyWeavers.xml file.

I don't think it ever should. I mean, it could be an opt-out feature. Not only for people who are trying to make a solution wide .xsd, but also for people who uses the debug-release workaround I mentioned, which is not changed by Fody, making it inconsistent. If Fody only changes files named `FodyWeavers.xml`, I'll still need to check every project to manually make the automatic changes. Perhaps there could be a list of file names where I could both add the extra files or make the list empty.

**Comment by Logerfo** [comment] 2018-11-28 13:03
Sorry, I forgot to answer your questions.

> Why do you want to use Fody without weavers? This is reported as an error because in most cases it is one. The fix for this is to uninstall Fody in projects where you don't need it.

I find it more consistent to make Fody enabled by default in every project of my solution, even if the weavers xml is empty. If someone needs it, it's there. Otherwise, someone will need to install it and mistakes could be made, like installing a different version from the others. Besides that, empty xml files are a thing even for projects which actually has weavers, because of the workaround I mentioned. I may have no weavers in debug mode, but one weaver in release mode, for example. As for the performance issue you mentioned, I don't really care much about the compile time. It's a fair trade for me.

> Why don't you want to have one xsd file next to each FodyWeavers.xml file? This is the usage that Fody supports.

I thought they were supposed to be identical. Are they? If they are, then it's just a "no code repetition" measure. If they are not, my mistake. But if they are not necessary, as it seems, I might keep it that way. I'm updating the package to get bugs fixed, performance improvements, etc. I don't want new stuff popping up in my repo unless I opt-in for those.

**Comment by tom-englert** [comment] 2018-11-28 13:09
@Logerfo no, they are not identical, every .xsd contains exactly the weavers that are installed for the individual project, so they reflect what you can add and what not.

**Comment by ltrzesniewski** [comment] 2018-11-28 13:10
The "real" fix there would be to implement a config property in Costura to deactivate it in debug builds. It should be pretty easy to do actually. I've already written a method to detect if an assembly is built in Debug mode [here](https://github.com/ltrzesniewski/InlineIL.Fody/blob/7ff9d4fc56de05e56630caa00170a992358f5074/src/InlineIL.Fody/Extensions/CecilExtensions.cs#L328-L352). So this is mostly a matter of adding an `if` check to Costura, really. Maybe you'd like to contribute a PR? 😉 

If you're only using Costura then `<DisableFody Condition="'$(Configuration)' == 'Debug'">true</DisableFody>` is a better workaround than the comment you refereed to.

> I thought they were supposed to be identical. Are they? 

Nope. They're generated based on the weavers that are referenced in your project.

**Comment by ltrzesniewski** [comment] 2018-11-28 13:35
> I'm still getting a "invalid child element" warning, though. And I know why: the "invalid" element is not a nuget weaver, but a weaver that I've made myself, and it's located at one of my projects in this solution. Is this not supported?

Oops. That looks like a bug, indeed.

> the last time I made a PR for Fody, it was rejected for not having tests, which I'm not willing to do.

Well, I don't really know what to say here... This is non-negotiable. Tests help ensure continued code quality and minimize regressions. If you want to have a good and stable product in the end, tests are necessary.

Each code change _must_ be tested, and this rule applies to just about any project, not just Fody.

**Comment by Logerfo** [comment] 2018-11-28 13:58
> Each code change must be tested,

In Costura, the only tests that exists for bool attributes like `DisableCompression` and `IncludeDebugSymbols` are for [`ConfigReader`](https://github.com/Fody/Costura/blob/f061314d56e62f7cb66015194e59eb1f3b461ac6/Tests/ConfigReaderTests.cs), not for the feature itself. This is not only contradicting what you said, but makes it hard to find an example to use as a starting point to make a test myself.

**Comment by ltrzesniewski** [comment] 2018-11-28 20:18
This doesn't mean we shouldn't hold new stuff to a high standard :)

**Comment by tom-englert** [comment] 2018-11-29 08:05
@Logerfo 
RE: *I'm still getting a "invalid child element" warning, though. And I know why: the "invalid" element is not a nuget weaver, but a weaver that I've made myself, and it's located at one of my projects in this solution. Is this not supported?*

This is only supported for backward compatibility. To get full support for the new features, see:
https://github.com/Fody/Fody/wiki/AddinSearchPaths

**Comment by Logerfo** [comment] 2018-11-29 13:03
@tom-englert I was not aware that "InSolutionWeaving" was deprecated. I followed the steps you mentioned, but it wasn't successful. Look what my .csproj looks like:
```xml
<ItemGroup>
    <WeaverFiles Include="$(SolutionDir)Weavers\bin\$(Configuration)\Weavers.dll" />
</ItemGroup>
```  
`Weavers` is a project with multiple weavers. This is what gets printed in the .xsd file:
```xml
<xs:element name="Weavers" minOccurs="0" maxOccurs="1" type="xs:anyType" />
```
But there is no weaver named `Weavers`, so I still get the warning, since the actual weaver names are not listed as valid elements. Is this not supported or am I missing something?

**Closed** 2018-12-04 09:43 UTC
