### ISSUE TITLE
Fody no longer weaving after 2.2.1?

### ISSUE THREAD

**Issue by PaddySe** [Fody/Fody#520] opened 2018-04-17 13:26 UTC
Is there a special trick to get Fody 2.3.0+ to work? I upgraded a solution from 2.1.0 to 3.0.3, and I immediately started getting errors from Anotar.Serilog.Fody about LogTo.Information throwing NotImplementedExpections. So I created a new, empty Class Library (.Net Framework), for 4.6.2 to test this:

1. I add the latest stable version of Anotar.Serilog.Fody, and upgrade all dependencies to their latest stable versions (which is Fody 3.0.3).
2. I add FodyWeavers.xml and add Anotar.Serilog to it.
3. In a simple class, I add a one-line method with `LogTo.Information("Hello, World!");` in it, with appropriate usings.
4. Compile.

During compilation, the normal Fody output about Fody doing stuff is not displayed, and when I decompile the file with dotPeek, it just shows the un-altered code, as it is in VS2017 (with latest updates installed).

If I downgrade Fody to 2.2.1, everything works as expected, I get the normal "Fody: Fody (version 2.2.1.0) Executing" output while compiling, and the decompiled .dll file shows the method has been "re-woven".

If I upgrade Fody to 2.3.0, it stops weaving.

So, is there a special trick to getting Fody working with versions higher than 2.2.1? Is there an upgrade or setup page somewhere I'm not able to find?

**Comment by SimonCropp** [comment] 2018-04-18 10:31
upload a repro

**Comment by DanielEgbers** [comment] 2018-04-18 12:29
I also noticed that **some** projects are no longer weaving, after I upgraded all my projects to Fody 3.0.

After comparing the projects I found the cause of this problem:
Fody is not weaving if ```<TargetFrameworks>``` (with **s**) of the new csproj-format contains only one target (e.g. ```<TargetFrameworks>net462</TargetFrameworks>```)

```<TargetFramework>net462</TargetFramework>```(whithout **s**) and ```<TargetFrameworks>net462;net47</TargetFrameworks>``` (with **s**) work

**Comment by SimonCropp** [comment] 2018-04-18 22:36
That sounds like an msbuild bug

**Comment by SimonCropp** [comment] 2018-04-21 10:15
Ok closing till someone uploads a repro

**Closed by SimonCropp** 2018-04-21 10:15 UTC
