### ISSUE TITLE
Visual Studio 2017 RC cannot find Microsoft.Build.Framework

### ISSUE THREAD

**Issue by clmcgrath** [Fody/Fody#277] opened 2016-11-17 05:03 UTC
Cross posting from the Costura repo where I originally posted this 
https://github.com/Fody/Costura/issues/173

Seems that an unmodified project that is building fine in  VS2015 using Costura.Fody can't find the Microsoft Build framework and throws the following exception at compile time 

```
Error       Fody: An unhandled exception occurred:
Exception:
Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace:

Server stack trace: 
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at IInnerWeaver.set_Logger(ILogger value)
   at Processor.ExecuteInOwnAppDomain() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 146
   at Processor.Inner() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 93
   at Processor.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 45
Source:
mscorlib
TargetSite:
Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
StackTrace: DiagnosticsSharp.Runner 
````

**Comment by kamil-mrzyglod** [comment] 2016-11-17 07:49
Since `Fody` directly references `Microsoft.Build.Framework` from `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Microsoft.Build.Framework.dll` can you confirm, that you have .NET Framework 4.5 installed on your computer?

**Comment by clmcgrath** [comment] 2016-11-17 14:51
Most definitely this is my main dev machine and this builds in Visual Studio 2015 on the same machine 
[environment.txt](https://github.com/Fody/Fody/files/597649/environment.txt)

**Comment by clmcgrath** [comment] 2016-11-17 14:56
This is running Windows 10 with anniversary update as well

**Comment by kamil-mrzyglod** [comment] 2016-11-17 15:49
I have such config on my work PC so I can check this tomorrow I think.

**Comment by kamil-mrzyglod** [comment] 2016-11-18 15:36
@clmcgrath I checked this on a clean solution on my laptop with Windows 10 and Visual Studio 2017 RC 5 and Fody works perfectly fine(run both `Costura` and mine `Seal` weaver).

Can you post an MWE of your problem? 

Could you tell what .NET version you have installed on your computer?

**Comment by clmcgrath** [comment] 2016-11-18 21:22
I did a full uninstall then  reinstall of the package and restarted windows and it finally seems to be working now (package restore did not fix it). i had to restart windows as something was hard locking the fody package folder, i also installed the multi targeting pack so not sure if that was what fixed it or not...  regardless the problem seems to be fixed now. will close the issue as this seems to be resolved

**Comment by rvhelden** [comment] 2017-02-09 10:32
I still have the same issue and I do have `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Microsoft.Build.Framework.dll`

Have tried the solution of @clmcgrath but doesn't work for me.

Another project with fody builds correctly (also in VS 2017 RC.4 26206.0) 

I have the following stacktrace:

```
1>    Fody (version 1.28.3.0) Executing
1>MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
1>MSBUILD : error : StackTrace:
1>MSBUILD : error : 
1>MSBUILD : error : Server stack trace: 
1>MSBUILD : error :    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
1>MSBUILD : error :    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
1>MSBUILD : error :    at System.Reflection.RuntimeMethodInfo.GetParameters()
1>MSBUILD : error :    at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
1>MSBUILD : error : 
1>MSBUILD : error : Exception rethrown at [0]: 
1>MSBUILD : error :    at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
1>MSBUILD : error :    at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
1>MSBUILD : error :    at IInnerWeaver.set_Logger(ILogger value)
1>MSBUILD : error :    at Processor.ExecuteInOwnAppDomain() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 146
1>MSBUILD : error :    at Processor.Inner() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 93
1>MSBUILD : error :    at Processor.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\Fody\Processor.cs:line 45
1>MSBUILD : error : Source:
1>MSBUILD : error : mscorlib
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
1>MSBUILD : error : Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
1>MSBUILD : error : StackTrace:
1>MSBUILD : error : 
1>MSBUILD : error : 
1>      Finished Fody 101ms.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

VS configuration

```
Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26206.0 D15REL
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Visual Basic 2017 RC   00369-50000-00000-AA061
Microsoft Visual Basic 2017 RC

Visual C# 2017 RC   00369-50000-00000-AA061
Microsoft Visual C# 2017 RC

Advanced Installer Extension   13.5
Advanced Installer Extension. For more information visit the Advanced Installer website at www.advancedinstaller.com. Copyright © Caphyon LTD. All rights reserved.

ASP.NET and Web Tools 2017   15.0.30206.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50127.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30126.0
Azure App Service Tools v3.0.0

Child Process Debugging Power Tool   1.0
Power tool to add child process debugging to Visual Studio.

Command Task Runner   1.2.34
Adds support for command line batch files in Visual Studio 2015's Task Runner Explorer. Supports .cmd, .bat, .ps1 and .psm1 files.

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CreateLayoutWizard   1.0
Create layout wizard.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

GhostDoc   5.4.16325.0
GhostDoc automatically generates XML documentation comments.

GitHub.VisualStudio   2.2.0.6
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper Ultimate 2016.3.2    Build 107.0.20170126.120331
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2017 JetBrains, Inc.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Merq   1.1.13-alpha (2f64b6d)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   Mono.Debugging.VisualStudio
Support for debugging Mono processes with Visual Studio.

NPM Task Runner   1.4.81
Adds support for npm scripts defined in package.json directly in Visual Studio's Task Runner Explorer. Includes full support for Yarn

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61701.270
Microsoft SQL Server Data Tools

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

Visual Studio Tools for Apache Cordova   15.110.00.00
Visual Studio Tools for Apache Cordova

Xamarin   4.3.0.664 (f42aa37)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   7.1.0.31 (c9880f9)
Visual Studio extension to enable development for Xamarin.Android.

Xamarin.Android SDK   7.1.0.31 (c9880f9)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS   10.4.0.102 (20d957a)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS and Xamarin.Mac SDK   10.4.0.102 (20d957a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by kamil-mrzyglod** [comment] 2017-02-09 14:18
@rvhelden Against which version of .NET framework you're building your solution?

**Comment by rvhelden** [comment] 2017-02-09 14:24
The project is currently build against .NET Framework 4.5.2

**Comment by kamil-mrzyglod** [comment] 2017-02-09 14:42
Could you post a solution which reproduces your problem?

**Comment by rvhelden** [comment] 2017-02-09 15:15
Sorry I have found the problem, my project was using an older version of Fody, i have upgraded the package to version 29 and everything is working now

**Comment by alvillain** [comment] 2017-02-17 10:23
I have the same issue using Costura.Fody 1.3.3.0. @rvhelden's solution is working for me. Thanks.

**Comment by Keboo** [comment] 2017-02-19 06:31
I ran into a similar issue this evening and did some investigation that I hope will provide useful information to others.. 

Here is the relevant portion from the MSBuild output
```
3>Task "Fody.WeavingTask"
3>    Fody: Fody (version 1.29.4.0) Executing
3>    Fody: ProjectDirectory: 'C:\Dev\AutoDI\AssemblyToProcess\'.
3>    Fody: AssemblyPath: 'C:\Dev\AutoDI\AssemblyToProcess\obj\Debug\AssemblyToProcess.dll'
3>    Fody: Found path to weavers file 'C:\Dev\AutoDI\AssemblyToProcess\FodyWeavers.xml'.
3>    Fody: SolutionDirectory path is 'C:\Dev\AutoDI\'
3>    Fody: Finding weavers
3>    Fody: Adding weaver dlls from 'C:\Dev\AutoDI\Packages'.
3>    Fody: Fody weaver file added 'C:\Dev\AutoDI\Packages\AutoDI.Fody.1.0.0\AutoDI.Fody.dll'
3>    Fody: Could not find packages dir from nuget config.
3>    Fody: SolutionDirectoryPath: C:\Dev\AutoDI\
3>    Fody: Adding weaver dlls from 'C:\Dev\AutoDI\packages'.
3>    Fody: Fody weaver file added 'C:\Dev\AutoDI\packages\AutoDI.Fody.1.0.0\AutoDI.Fody.dll'
3>    Fody: SolutionDirectoryPath: C:\Dev\AutoDI\
3>    Fody: Skipped scanning 'C:\Dev\AutoDI\Tools' for weavers since it doesn't exist.
3>    Fody: No Weaver project file found.
3>    Fody: Finished finding weavers 23ms
3>    Fody: A Weaver HasChanged so loading a new AppDomain
3>    Fody: Creating a new AppDomain
3>    Fody: Reference count=11
3>    Fody: Found debug symbols at 'C:\Dev\AutoDI\AssemblyToProcess\obj\Debug\AssemblyToProcess.pdb'.
3>    Fody: Weaver 'C:\Dev\AutoDI\Packages\AutoDI.Fody.1.0.0\AutoDI.Fody.dll'.
3>    Fody:   Initializing weaver
3>    Fody:   Loading 'C:\Dev\AutoDI\Packages\AutoDI.Fody.1.0.0\AutoDI.Fody.dll' from disk.
3>MSBUILD : error : Fody: An unhandled exception occurred:
3>MSBUILD : error : Exception:
3>MSBUILD : error : Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
3>MSBUILD : error : StackTrace:
3>MSBUILD : error :    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
3>MSBUILD : error :    at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
3>MSBUILD : error :    at System.Reflection.RuntimeMethodInfo.GetParametersNoCopy()
3>MSBUILD : error :    at System.Reflection.RuntimePropertyInfo.GetIndexParametersNoCopy()
3>MSBUILD : error :    at System.Reflection.RuntimePropertyInfo.GetIndexParameters()
3>MSBUILD : error :    at System.RuntimeType.GetPropertyCandidates(String name, BindingFlags bindingAttr, Type[] types, Boolean allowPrefixLookup)
3>MSBUILD : error :    at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
3>MSBUILD : error :    at System.Type.GetProperty(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
3>MSBUILD : error :    at PropertyDelegateBuilder.TryBuildPropertySetDelegate[T](Type targetType, String propertyName, Action`2& action) in C:\projects\fody\FodyIsolated\DelegateBuilders\PropertyDelegateBuilder.cs:line 18
3>MSBUILD : error :    at DelegateBuilder.BuildDelegateHolder(Type weaverType) in C:\projects\fody\FodyIsolated\DelegateBuilders\DelegateBuilder.cs:line 31
3>MSBUILD : error :    at DelegateBuilder.GetDelegateHolderFromCache(Type weaverType) in C:\projects\fody\FodyIsolated\DelegateBuilders\DelegateBuilder.cs:line 15
3>MSBUILD : error :    at InnerWeaver.InitialiseWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 120
3>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 81
3>MSBUILD : error : Source:
3>MSBUILD : error : mscorlib
3>MSBUILD : error : TargetSite:
3>MSBUILD : error : Void GetSignature(Void*, Int32, System.RuntimeFieldHandleInternal, System.IRuntimeMethodInfo, System.RuntimeType)
3>MSBUILD : error : Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
3>MSBUILD : error : 
3>    Fody:   Finished Fody 902ms.
3>Done executing task "Fody.WeavingTask" -- FAILED.
```

Clearly something is failing to load the Microsoft.Build.Framework assembly. 
Examining my weaver I can see that it is compiled against version 4.0.0.0
(ILDasm)
```
.assembly extern Microsoft.Build.Framework
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:0:0:0
}
```

Firing up Fuslog the problem is a little more clear:
```
*** Assembly Binder Log Entry  (2/18/2017 @ 10:15:50 PM) ***

The operation failed.
Bind result: hr = 0x80070002. The system cannot find the file specified.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Dev/AutoDI/packages/Fody.1.29.4
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = MSBuild.exe
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.0.0.0 redirected to 15.1.0.0.
LOG: Post-policy reference: Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Dev/AutoDI/packages/Fody.1.29.4/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///C:/Dev/AutoDI/packages/Fody.1.29.4/Microsoft.Build.Framework/Microsoft.Build.Framework.DLL.
LOG: Attempting download of new URL file:///C:/Dev/AutoDI/packages/Fody.1.29.4/Microsoft.Build.Framework.EXE.
LOG: Attempting download of new URL file:///C:/Dev/AutoDI/packages/Fody.1.29.4/Microsoft.Build.Framework/Microsoft.Build.Framework.EXE.
LOG: All probing URLs attempted and failed.
```

Of particular interest are these two lines:
```
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.Config
LOG: Redirect found in application configuration file: 4.0.0.0 redirected to 15.1.0.0.
```

Looking into the new MSBuild.exe.config file and sure enough there is a binding redirect to forward all versions of Microsoft.Build.Framework to version 15.1.0.0

So I then decided to take a peek to see why my weaver was relying on the Microsoft.Build.Framework. As it turns out I had started my weaver by copying the default weaver which contains this line:
```C#
// Will log a message to MSBuild. OPTIONAL
public Action<string, MessageImportance> LogMessage { get; set; }
```

The `MessageImportance` class lives in the Microsoft.Build.Framework. Since I was not using this property I simply removed it and the reference to Microsoft.Build.Framework and my problem was solved. However I suspect this issue may end up breaking other weavers.

Looking into it more, it appears that Fody loads the weaver assemblies from byte arrays which causes them to be loaded [without context](https://msdn.microsoft.com/en-us/library/dd153782(v=vs.110).aspx#load_contexts). Which I suspect this is likely the reason for it not being able to resolve the dependency. Any thoughts on how this could be addressed?

**Comment by kamil-mrzyglod** [comment] 2017-02-19 09:50
In fact whole `Logger` class depends on this assembly because it uses it to log messages to the build output.

**Comment by Keboo** [comment] 2017-02-19 16:36
True, but I think it is important to point out he difference between [assembly binding](https://msdn.microsoft.com/en-us/library/yx7xezcf(v=vs.110).aspx) between Fody itself and the weavers that it loads.

Fody itself is an MSBuild task that is loaded as part of the build process. The weavers are loaded with calls to [Assembly.Load(byte[])](https://msdn.microsoft.com/en-us/library/h538bck7(v=vs.110).aspx). This means that if there is a binding redirect provided by MSBuild.exe.config that the weavers will not get it since they are being loaded [without context](https://msdn.microsoft.com/en-us/library/dd153782(v=vs.110).aspx#load_contexts) (which is what I believe is the problem here). So the reference between Fody and Microsoft.Build.Framework is fine, the issue comes when a weaver also references it (which is what the [example weaver](https://github.com/Fody/Fody/blob/master/SampleTask.Fody/ModuleWeaver.cs) does)

**Comment by kamil-mrzyglod** [comment] 2017-02-20 09:15
@Keboo Sure but I assume such change(loading weaver with context) is potentially a breaking change(I can easily imagine that this hid some bugs and with this change many things could explode). @SimonCropp - any thoughts on this?

**Comment by 0x53A** [comment] 2017-03-08 17:14
Just wanted to mention that I hit the same issue - we use a custom weaver (written by me), and when building, MSBuild from VS2017 crashed hard. After removing the reference to ``Microsoft.Build.Framework`` inside the weaver, it now compiles Ok.

**Comment by atzimler** [comment] 2017-03-14 05:42
I've just run into this problem today. It seems to go away if you install MSBuild version 14 - which is the one associated with VS2015. https://www.microsoft.com/en-us/download/details.aspx?id=48159

**Comment by aherrick** [comment] 2017-03-15 17:25
@atzimler Running into the same thing. Is installing 14 really the right way to go here? I don't want that to mess with other things.

Thanks!

**Comment by atzimler** [comment] 2017-03-15 21:53
@aherrick Not necessarily the right way. The error was still randomly popping up after that, so I also updated the Fody package to the latest and the Fody tools too. Technically that should not cause any problem on the projects you are working, because the tools should not link against your project, just edit them. You could try to solve the problem starting with the upgrade. Now the solution I'm working on seems to compile all the time, but I haven't been able to run everything through our build server, because I'm working on a branch that still needs modifications. Our build server only has MSBuild 4 that comes from VS2012, so that will confirm if only upgrading Fody and the tools themselves solves the problem.

**Comment by aherrick** [comment] 2017-03-15 22:28
@atzimler thanks for the response!

**Comment by jhendricks123** [comment] 2017-04-24 17:32
Ran into problems using Costura.Fody today as well on an existing VS2015 project where it was already installed. I tried reinstalling the package but the issue persisted. I then removed it and reinstalled it using VS2015 and it built fine again, so for now I will just stick to VS2015 for that project.

I opened an existing VS2017 project, installed Costura.Fody and it built successfully.

I opened an existing VS2015 project where the package was never installed, installed it, and it failed in the same way.

It seems like the issue is specifically with projects originally developed under VS2015, but I don't know enough about the package, or typical VS version migration challenges to diagnose further.

**Comment by SimonCropp** [comment] 2017-04-24 23:16
@jhendricks123 is it only costura?

**Comment by jhendricks123** [comment] 2017-04-25 02:43
Costura.Fody is pretty much black magic to me, so I'm not sure. I'll check again tomorrow.

I'm pretty sure I can have a Fody dependency installed without causing build errors, but with the Costura.Fody package installed, it only builds on 2017 if the project started as a VS2017 project in the first place.

**Comment by SimonCropp** [comment] 2017-04-27 09:36
@distantcam thoughts?

**Comment by distantcam** [comment] 2017-04-27 09:44
The original issue Fody/Costura#173 was closed after the poster updated the Fody package. Costura 1.4 now references the newer Fody packages so this shouldn't be an issue any longer.

Close this?

**Comment by SimonCropp** [comment] 2017-04-27 09:49
ok

**Closed by SimonCropp** 2017-04-27 09:49 UTC
