### ISSUE TITLE
Out of Memory in Xamarin Studio and Visual Studio for Mac

### ISSUE THREAD

**Issue by JCKodel** [Fody/Fody#302] opened 2017-04-09 05:03 UTC
When building a Xamarin Forms project:

```
Error: Fody: An unhandled exception occurred:
Exception:
Out of memory
StackTrace:
  at (wrapper alloc) System.Object:AllocVector (intptr,intptr)
  at Microsoft.Cci.Pdb.MsfDirectory..ctor (Microsoft.Cci.Pdb.PdbReader reader, Microsoft.Cci.Pdb.PdbFileHeader head, Microsoft.Cci.Pdb.BitAccess bits) [0x000a5] in <d39e61ae2787473a851567b860d13696>:0 
  at Microsoft.Cci.Pdb.PdbFile.LoadFunctions (System.IO.Stream read, System.Collections.Generic.Dictionary`2[System.UInt32,Microsoft.Cci.Pdb.PdbTokenLine]& tokenToSourceMapping, System.String& sourceServerData, System.Int32& age, System.Guid& guid) [0x00027] in <d39e61ae2787473a851567b860d13696>:0 
  at Mono.Cecil.Pdb.PdbReader.PopulateFunctions () [0x00008] in <d39e61ae2787473a851567b860d13696>:0 
  at Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader (Mono.Cecil.Cil.ImageDebugDirectory directory, System.Byte[] header) [0x00048] in <d39e61ae2787473a851567b860d13696>:0 
  at Mono.Cecil.ModuleDefinition.ProcessDebugHeader () [0x00012] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleDefinition.ReadSymbols (Mono.Cecil.Cil.ISymbolReader reader) [0x00015] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleReader.ReadSymbols (Mono.Cecil.ModuleDefinition module, Mono.Cecil.ReaderParameters parameters) [0x00047] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleReader.CreateModuleFrom (Mono.Cecil.PE.Image image, Mono.Cecil.ReaderParameters parameters) [0x00076] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream, Mono.Cecil.ReaderParameters parameters) [0x00028] in <b5a52cab1f0046ce9f68342127787868>:0 
  at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters) [0x0000a] in <b5a52cab1f0046ce9f68342127787868>:0 
  at InnerWeaver.ReadModule () [0x00052] in <f6f9069078364b4db60945017a527c4a>:0 
  at InnerWeaver.Execute () [0x00019] in <f6f9069078364b4db60945017a527c4a>:0 
 ([Solution's Name])
```

It takes less than 2 seconds to crash. There is plenty of memory available:

```
Hardware Overview:

  Model Name:	iMac
  Model Identifier:	iMac14,2
  Processor Name:	Intel Core i7
  Processor Speed:	4,01 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	32 GB
```

**Comment by kanvuduc** [comment] 2017-04-09 11:14
I also face this issue. I logged [an issue](https://github.com/realm/realm-dotnet/issues/1342) on a Realm repo.

**Comment by kanvuduc** [comment] 2017-04-09 11:31
Change .NET Runtime to v4.8 in Xamarin Studio/VS for Mac Preference will be a workaroud
<img width="963" alt="screen shot 2017-04-09 at 6 30 43 pm" src="https://cloud.githubusercontent.com/assets/3112460/24836920/b981ada0-1d52-11e7-8968-84fc2e238349.png">

**Comment by bbkillen** [comment] 2017-04-09 17:45
kanvuduc's solution fixed my problem and saved my bacon!!!

**Comment by stefandevo** [comment] 2017-04-11 10:56
I reported this on the mono. [bugzilla](https://bugzilla.xamarin.com/show_bug.cgi?id=55016)

**Comment by stefandevo** [comment] 2017-04-11 11:31
And now moved to [https://github.com/jbevain/cecil/issues/378](https://github.com/jbevain/cecil/issues/378) as Mono group is pointing to Cecil as the cause.

**Comment by stefandevo** [comment] 2017-04-11 14:40
And now Cecil is pointing to Fody again [https://github.com/jbevain/cecil/issues/378#event-1038391109](https://github.com/jbevain/cecil/issues/378#event-1038391109).

Is using Fody v0.9 or v.10 ?

**Comment by stefandevo** [comment] 2017-04-11 14:53
So I checked the latest nuget packages for Fody. 1.29.4 en 1.30.0-beta01 are coming with Mono.Cecil.dll version 0.9.6.0; so this is the problem (according to Mono.Cecil).

However, in [https://github.com/Fody/Fody/tree/master/Lib/Cecil](https://github.com/Fody/Fody/tree/master/Lib/Cecil) I see the that the version is 0.10.0 ... 

Is it possible to create a new update for fody packaging this latest version?

**Comment by hrach** [comment] 2017-04-11 19:49
Any idea for workaround in Visual Studio on Windows?

**Comment by bbkillen** [comment] 2017-04-11 20:15
I fixed this in VS4M in the preferences…

**Comment by Lenndev** [comment] 2017-04-12 19:57
Pointing to each other doesn't help... what does help is the "work around" @kanvuduc mentioned. In VS > preferences > .NET runtimes  > set Mono 4.8.0 as default

**Comment by hrach** [comment] 2017-04-12 20:01
Well, on Windows, there is not such configuraiton, since there is not a mono, am I right?

@Lenndev nobody is "pointing", people just try to find the cause and get it logged into a proper issue tracker.

**Comment by stefandevo** [comment] 2017-04-12 20:26
Fixing it for now is ok, but for example on VSforMac or XS this means you cannot use c# 7 in combination with Fody with doesn't make me happy...

**Comment by galvesribeiro** [comment] 2017-04-13 23:25
+1 with the same issue... Sad to hear we can't use C#7 + Fody :(

**Comment by dansiegel** [comment] 2017-04-14 04:15
It seems like this is causing major havoc for a lot of dev's... so glad it's not just me. It seems that the root of this is Cecil, however it is also a Fody problem due to the way in which Fody ships with no dependencies by including Cecil as part of the package. Supposedly the [issue](https://github.com/jbevain/cecil/issues/379#issuecomment-294030980) should be fixed in 0.10-beta5, however Fody would need to release an updated package with the new Cecil binaries.

**Comment by Redth** [comment] 2017-04-18 12:38
This is going to break any Xamarin dev using Fody very soon.  It looks unfortunately like this project is a bit dead.  I took a quick look at merging in the upstream Cecil changes back into Fody's fork, and it looks like *maybe* Cecil now includes the functionality Fody had added to their fork, so perhaps it's possible to use Cecil as a true dependency.  I may have an extended look at this over the next few days.

**Comment by Bartmax** [comment] 2017-04-20 17:30
> This is going to break any Xamarin dev using Fody very soon.

Yup, add one more to the list.

**Comment by renzska** [comment] 2017-04-20 17:43
Sadly, like @kanvuduc mentioned, this breaks the usage of Realm. We were about to start using it in a new app, but now we have to find something else. Any recommendations besides sqllite?

**Comment by galvesribeiro** [comment] 2017-04-20 17:59
@renzska same case here... Thats why libraries should avoid at all cost to don't take dependencies on 3rd party libraries... It will break Realm all over...

**Comment by stefandevo** [comment] 2017-04-20 19:04
https://github.com/Fody/PropertyChanged/issues/226

**Comment by SimonCropp** [comment] 2017-04-22 15:42
Can u try fody 2.0

**Comment by dansiegel** [comment] 2017-04-22 17:51
@SimonCropp testing this with PropertyChanged in VS for Mac everything looks like it's working right again. Thanks for getting the update out!

**Comment by SimonCropp** [comment] 2017-04-22 19:59
Good to hear

**Closed** 2017-04-22 20:00 UTC

**Comment by kanvuduc** [comment] 2017-08-12 09:02
@ismly Here you are http://www.mono-project.com/docs/about-mono/releases/4.8.0/
